/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ArbitrageBettingCalculator: typeof import('./src/components/arbitrage-betting-calculator/arbitrage-betting-calculator.vue')['default']
    ArbitrageHeader: typeof import('./src/components/arbitrage-betting-calculator/arbitrage-header/arbitrage-header.vue')['default']
    Card: typeof import('./src/components/MainPageView/card/card.vue')['default']
    DayResult: typeof import('./src/components/MainPageView/result-box-body/DayResult.vue')['default']
    DeckOfCards: typeof import('./src/components/MainPageView/DeckOfCards/DeckOfCards.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElRow: typeof import('element-plus/es')['ElRow']
    HeaderButton: typeof import('./src/components/header/header-button/header-button.vue')['default']
    LineChart: typeof import('./src/components/MainPageView/line-chart/line-chart.vue')['default']
    LoginPage: typeof import('./src/components/LoginPage/LoginPage.vue')['default']
    MainHeader: typeof import('./src/components/header/main-header.vue')['default']
    MainPageView: typeof import('./src/components/MainPageView/MainPageView.vue')['default']
    ModifiableDropDownList: typeof import('./src/components/MainPageView/result-box-body/ModifiableDropDownList.vue')['default']
    ResultBox: typeof import('./src/components/MainPageView/result-box-body/ResultBox.vue')['default']
    ResultButton: typeof import('./src/components/result-button/result-button.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
