/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ArbitrageBettingCalculator: typeof import('./src/components/arbitrage-betting-calculator/arbitrage-betting-calculator.vue')['default']
    ArbitrageHeader: typeof import('./src/components/arbitrage-betting-calculator/arbitrage-header/arbitrage-header.vue')['default']
    Card: typeof import('./src/components/main-page-view/card/card.vue')['default']
    DayResult: typeof import('./src/components/main-page-view/result-box-body/DayResult.vue')['default']
    DeckOfCards: typeof import('./src/components/main-page-view/deck-of-cards/DeckOfCards.vue')['default']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    ElRow: typeof import('element-plus/es')['ElRow']
    HeaderButton: typeof import('./src/components/header/header-button/HeaderButton.vue')['default']
    LineChart: typeof import('./src/components/main-page-view/line-chart/LineChart.vue')['default']
    LoginPage: typeof import('./src/components/login-page/LoginPage.vue')['default']
    MainHeader: typeof import('./src/components/header/MainHeader.vue')['default']
    MainPageView: typeof import('./src/components/main-page-view/MainPageView.vue')['default']
    ResultBox: typeof import('./src/components/main-page-view/result-box-body/ResultBox.vue')['default']
    ResultButton: typeof import('./src/components/main-page-view/result-box-body/ResultButton.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SessionRegister: typeof import('./src/components/main-page-view/SessionRegister.vue')['default']
    SingleHand: typeof import('./src/components/main-page-view/result-box-body/SingleHand.vue')['default']
  }
}
